#! /bin/bash -e

cd erlide_debugger_17
./build "$@"
cd ../erlide_debugger_18
./build "$@"
cd ../erlide_debugger_19
./build "$@"
cd ../erlide_debugger_20
./build "$@"
cd ../erlide_debugger
./build "$@"

cd ..
